replicaCount: 2

image:
  repository: ghcr.io/cynest/timedrop
  tag: 1.1.4
  pullPolicy: Always

service:
  name: timedrop-service
  type: LoadBalancer
  port: 80
  targetPort: 9987

env:
  name: prod
