apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: timedrop
  name: {{ .Release.Name }}-timedrop
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: timedrop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: timedrop
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 9987
          protocol: TCP
