apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
          app.kubernetes.io/name: timedrop
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: timedrop
  ports:
    - name: http
      protocol: {{ .Values.service.protocol | default "TCP" }}
      # Port accessible inside cluster
      port: {{ .Values.service.port }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.service.targetPort }}
  externalIPs:
    # Change this to an external IP you have available if not in a cloud-provider.
    # If you're running on a cloud provider, comment out the entire externalIPs: section.
    - 192.168.1.202
